# Generated by Django 5.2 on 2025-04-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_model',
            name='brand',
            field=models.CharField(default='DefaultBrand', max_length=100),
        ),
        migrations.AddField(
            model_name='shop_model',
            name='category',
            field=models.CharField(choices=[('makeup', 'Makeup'), ('fashion', 'Fashion'), ('skincare', 'skincare'), ('electronics', 'Electronics')], default='Makeup', max_length=20),
        ),
        migrations.AddField(
            model_name='shop_model',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop_model',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
